### ISSUE TITLE
Fixed/min height textarea causes mentions list placement issue

### ISSUE THREAD

**Issue by trickeyone** [nth-cloud/ng-mentions#4]
```css
textarea {
    width: 100%;
    min-height: 155px;
    padding: 10px 14px;
    line-height: 1.3em;
    resize: none;
}
```
```html
<textarea rows="1" cols="20"></textarea>
```

Using min-height appears to be causing an issue with the placement of the mentions list. It appears about 60px too low when the textarea has scrollable text.
